### ISSUE TITLE
Ownership of @radiomodem Docker ID

### ISSUE THREAD

**Issue by kasperisager** [radiomodem/broadcast#1]
@radiomodem has an associated Docker ID used for publishing and distributing the radiomodem/broadcast Docker image. I'm however the only owner of this Docker ID and would therefore like to hand it over to someone active in the @radiomodem org.

**Comment by kasperisager** [comment]
@AsgarTheRedBaron @Dalleboi

**Comment by Dalleboi** [comment]
Thank you! I have no idea what this is though.

**Comment by kasperisager** [comment]
This: https://hub.docker.com/u/radiomodem

**Comment by Dalleboi** [comment]
Can you tell me a bit about what this is?

**Comment by kasperisager** [comment]
The broadcast server, which is based on Icecast, is deployed as a Docker image. There are basically two ways of distributing that image to the server at https://broadcast.radiomodem.dk/: 1) Build the image against the Docker daemon on the server or 2) build the image against your local Docker daemon, push it to https://hub.docker.com/r/radiomodem/broadcast, and have the server pull the image from there. The latter option is what the @radiomodem Docker ID is used for.

**Comment by kasperisager** [comment]
@Dalleboi ☝️

**Comment by Dalleboi** [comment]
Yeah ive read what youve said a couple of times now and I have no clue on what this problem is.

Få Outlook til Android<https://aka.ms/ghei36>

________________________________

**Comment by kasperisager** [comment]
Alright, I've nuked the Docker ID altogether to simplify things. Case closed!

**Comment by Dalleboi** [comment]
Dude we are design students, so to me this sounds like you did something bad.
Can you explain the nukeing to me like i was 5?

Få Outlook til Android<https://aka.ms/ghei36>

________________________________

**Comment by kasperisager** [comment]
My bad! It's nothing to worry about, I should have been clear on that 🙈 The short version is that you don't really need the thing I was looking to hand over anyway so I simply deleted it instead. All is well 😉

**Comment by Dalleboi** [comment]
Good lad thanks for the help haha !

Få Outlook til Android<https://aka.ms/ghei36>

________________________________
